Add ATE check.

diff --git a/.github/workflows/roman.yml b/.github/workflows/roman.yml
--- a/.github/workflows/roman.yml
+++ b/.github/workflows/roman.yml
@@ -77,7 +77,7 @@ jobs:
               -p demo/params/demo \
               -o demo_output 
 
-      - name: Check for sparkal1.pkl
+      - name: Check Mapping Output
         run: |
           if [ -f demo_output/map/sparkal1.pkl ]; then
             echo "✅ sparkal1.pkl was successfully created."
@@ -86,3 +86,21 @@ jobs:
             exit 1
           fi
 
+      
+      - name: Check ATE
+        run: |
+          ATE_FILE="$GITHUB_WORKSPACE/roman/demo_output/offline_rpgo/ate_rmse.txt"
+          if [ ! -f "$ATE_FILE" ]; then
+            echo "❌ ATE file not found at $ATE_FILE" >&2
+            exit 1
+          fi
+
+          ATE_VALUE=$(cat "$ATE_FILE")
+          echo "🔍 ATE RMSE value: $ATE_VALUE"
+          
+          if awk "BEGIN {exit !($ATE_VALUE < 1.5)}"; then
+            echo "✅ ATE RMSE is below threshold (1.5)"
+          else
+            echo "❌ ATE RMSE is above threshold (1.5)" >&2
+            exit 1
+          fi
